Server:
  appVersion: "1.0.0"
  host: "0.0.0.0"
  port: "8080"
  timeout: 4s
  idle_timeout: "60s"
  environment: "local"
  mode: "debug"

database:
  host: "url-shortener-postgres"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "url_shortener"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"

Redis:
  URL: "redis://notification-redis:6379"
  host: "url-shortener-redis"
  port: 6379
  password: ""  # для локального Redis
  db: 0

  # Настройки пула соединений
  max_retries: 3
  pool_size: 10
  min_idle_conns: 5
  max_idle_conns: 10
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"
  pool_timeout: "4s"

app:
  short_url_length: 6
  cache_ttl: "1h"
  base_url: "http://localhost:8080"