version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: comment-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - comment-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comment-service
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=production
    volumes:
       - ./config/:/root/config/
       - ./internal/web/templates:/app/internal/web/templates:ro
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - comment-network

volumes:
  redis_data:
    driver: local

networks:
  comment-network:
    driver: bridge