Server:
  appVersion: "1.0.0"
  host: "0.0.0.0"
  port: "8080"
  timeout: 4s
  idle_timeout: "60s"
  environment: "local"

Redis:
  URL: "redis://notification-redis:6379"
  host: "notification-redis"
  port: 6379
  password: ""  # для локального Redis
  db: 0

  # Настройки пула соединений
  max_retries: 3
  pool_size: 10
  min_idle_conns: 5
  max_idle_conns: 10
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"
  pool_timeout: "4s"
  idle_timeout: "5m"

Rabbit:
  # Полный URL (альтернатива раздельным настройкам)
  url: "amqp://guest:guest@notification-rabbitmq:5672/"
  
  # Раздельные настройки (если не используется url)
  host: "notification-rabbitmq"
  port: 5672
  username: "guest"
  password: "guest"
  exchange_name: "notifications_exchange"
  queue_name: "notifications"
  virtual_host: "/"